### ISSUE TITLE
Create a config file

### ISSUE THREAD

**Issue by shriaas2898** [JayKandari/bookhive#10]
Create config file to store:
* DB information
* URL paths, so that files can be dynamically accessed
* Site name 
* Statements for error reporting.

In case needed use [this](https://code.tutsplus.com/tutorials/organize-your-next-php-project-the-right-way--net-5873) for Reference

**Comment by AJV009** [comment]
@shriaas2898 maybe you should also move the site url param to a external file for more flexibility.
config.php
```php
...
//URL of the site you can add URLs for Log, Error etc.
    'urls' => array(
        'baseUrl' => $creds['sitename'] //cange according to your configuration
    ),
...
```
Cause I just mistakenly committed a different url with it and this can happen a million times
@shriaas2898 Should I make a PR on this?
AND I have also moved the path of dbcred.json to root
so that it becomes easy for any one to just hop in a use it
I have heard some kind of composer way to do these stuff automatically well we will keep that as an upgrade option

**Comment by AJV009** [comment]
@shriaas2898   Should I make a PR on this?

**Comment by AJV009** [comment]
AND I have also moved the path of dbcred.json to root
so that it becomes easy for any one to just hop in a use it
I have heard some kind of composer way to do these stuff automatically well we will keep that as an upgrade option
