### ISSUE TITLE
Create layout files

### ISSUE THREAD

**Issue by shriaas2898** [JayKandari/bookhive#11]
Create layout files for different blocks like:
* Header
* Footer
* Side bar etc
Create a file to combine a all the blocks from the layout file along with the actual content and render it.

**Comment by AJV009** [comment]
@shriaas2898 how is it exactly going to go, like?
Can we have a meeting on this after everybody makes there PRs and we have a mvp?

**Comment by shriaas2898** [comment]
Sure a meeting would be good

**Comment by AJV009** [comment]
Cause I have strong feeling that a lot of UI components made by Pragati will require a TON of changes, if we are going to go this way!
And also Anjali DB code too will require changes.
JUST my guess

**Comment by AJV009** [comment]
And I think we should discuss and layout some strong rules before making PR.
Ex. Every PR should make code/changes which can be used straight away by anyone without making modification.
Because making direct modification a million times in the master? I don't think that's a right way to do it!
(slack dm)

**Comment by AJV009** [comment]
Hey @shriaas2898 maybe close this issue as we don't have planning for layout files now!
