### ISSUE TITLE
Code Cleanup

### ISSUE THREAD

**Issue by JayKandari** [JayKandari/bookhive#27]
This issue is created to track any code cleanup which is present in the codebase and would be required. 

This is not an urgent task atm. But Needs to be taken care when the main functionality of the application starts working. 

Keep this issue open till all codebase is cleared. Multiple PRs can be referenced to this issue. 

Thanks!

**Comment by AJV009** [comment]
By code cleanup do you also mean any syntax based too?
Like beautify code?

**Comment by guptahemant** [comment]
beautify is the last thing, but can be done, Most of the things will include clear separation of logic, data handling and data representation, Currently lots of HTML has been stuffed in the classes directly whereas it should have been tried to separate the fetching of data in one function and rendering it with other. there are lots of consistency issues as well, in making use of session and database related classes appropriately, All these kind of things should be addressed here, If not done as part of other issues.

**Comment by AJV009** [comment]
> beautify is the last thing, but can be done, Most of the things will include clear separation of logic, data handling and data representation, Currently lots of HTML has been stuffed in the classes directly whereas it should have been tried to separate the fetching of data in one function and rendering it with other. there are lots of consistency issues as well, in making use of session and database related classes appropriately, All these kind of things should be addressed here, If not done as part of other issues.

Okay got it!
But now due to this first time collaborative project, we have already messed up a lot n' lot of logic! You will hate to see the mess.
But as the deadline is closing doing some major change doesn't seem feasible right now at least.
Even am having a tough time understanding others code, its quite difficult sometimes.
AND I almost missed to make proper documentation for the methods I made because of which it has become quite difficult for others use it. my bad
